version: 2
jobs:
  build:
    docker:
      - image: cloudmesh/book:1.0
    steps:
      - checkout
      - run:
          name: where
          command: ls; pwd
      - run:
          name: which python
          command: which python
      - run:
          name: python version
          command: python --version
      - run:
          name: pip version
          command: pip --version
      - run:
          name: pandoc version
          command: pandoc --version
      - run:
          name: changed files
          command: git diff-tree --no-commit-id --name-only -r HEAD > changed_files.log && cat changed_files.log
      - run:
          name: biber
          command: bin/check-biber.sh changed_files.log
      - run:
          name: epub
          command: make epub
      - store_artifacts:
          path: vonLaszewski-pi-cluster-case.epub
          destination: vonLaszewski-pi-cluster-case.epub
      - run:
          name: pdf
          command: make pdf
      - store_artifacts:
          path: vonLaszewski-pi-cluster-case.pdf
          destination: vonLaszewski-pi-cluster-case.pdf
