version: 2
jobs:
  build:
    docker:
      - image: cloudmesh/book:1.0
    steps:
      - checkout
      - run:
          name: where
          command: ls; pwd
      - run:
          name: which python
          command: which python
      - run:
          name: python version
          command: python --version
      - run:
          name: pip version
          command: pip --version
      - run:
          name: pandoc version
          command: pandoc --version
      - run:
          name: changed files
          command: git diff-tree --no-commit-id --name-only -r HEAD > changed_files.log && cat changed_files.log
      - run:
          name: biber
          command: bin/check-biber.sh changed_files.log
      - run:
          name: epub
          command: make epub
      - store_artifacts:
          path: vonLaszewski-pi-cluster-case.epub
          destination: vonLaszewski-pi-cluster-case.epub
#      - run: |
#           VERSION=$CIRCLE_TAG
#           if [ -z "$CIRCLE_TAG" ]; then VERSION="$CIRCLE_BRANCH-$(echo $CIRCLE_SHA1 | cut -c -7)"; fi
#           echo "VERSION=$VERSION"
#           echo "export VERSION=$VERSION" >> $BASH_ENV

#     - run:
#          name: pdf
#          command: make pdf
#     - store_artifacts:
#          path: vonLaszewski-pi-cluster-case.pdf
#          destination: vonLaszewski-pi-cluster-case.pdf

  publish:
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: ./artifacts      
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
workflows:
  version: 2
  deploy:
    jobs:
      - build
      - publish:
          requires:
            - build